version: '3'

services:
  db:
    image: postgres
  web:
    image: bmdssoftware/orals:latest
    command: bash -c "rm /code/tmp/pids/server.pid && ./start.sh "
    volumes:
      - .:/code
      - gems:/gems
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  gems:
    driver: local
